name: riverpod_persistence
description: A new Flutter package project.
version: 0.0.6
homepage: https://github.com/tim-smart/riverpod_persistence

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  fpdt: ^0.0.41
  riverpod: ^1.0.3
  shared_preferences: ^2.0.13

dev_dependencies:
  flutter_lints: ^2.0.0
  test: any
